version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: smartstitch
      POSTGRES_PASSWORD: smartstitch
      POSTGRES_DB: smartstitch
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
